# ── Stage 1: Dependencies ──────────────────────────────────
FROM node:20-alpine AS deps

WORKDIR /app
RUN corepack enable

COPY package.json yarn.lock* .yarnrc.yml* ./
RUN yarn install --frozen-lockfile

# ── Stage 2: Build ─────────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app
RUN corepack enable

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time env vars (prevents API calls during build)
ENV NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=pk_7f41b345f0191e6f857d1f707ff179e6425dc35c6b33f9846c6abdcca208fd47
ENV NEXT_TELEMETRY_DISABLED=1

RUN yarn build

# ── Stage 3: Runtime ───────────────────────────────────────
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8000
ENV HOSTNAME="0.0.0.0"

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy only what standalone needs:
# 1. public folder (static assets)
COPY --from=builder /app/public ./public

# 2. Standalone server + node_modules (minimal)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# 3. Static assets generated by Next.js
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 8000

CMD ["node", "server.js"]
